services:
  postgres:
    image: postgres:16
    container_name: painting_postgres
    restart: always

    environment:
      POSTGRES_DB: painting_db
      POSTGRES_USER: painting_user
      POSTGRES_PASSWORD: painting_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: