# Generated by Django 5.1.6 on 2026-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_convert_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label_english', models.CharField(max_length=100)),
                ('label_german', models.CharField(max_length=100)),
                ('label_ukrainian', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_english', models.CharField(max_length=200)),
                ('degree_german', models.CharField(max_length=200)),
                ('degree_ukrainian', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('description_english', models.TextField(blank=True, default='')),
                ('description_german', models.TextField(blank=True, default='')),
                ('description_ukrainian', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_english', models.CharField(max_length=200)),
                ('position_german', models.CharField(max_length=200)),
                ('position_ukrainian', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('description_english', models.TextField(blank=True, default='')),
                ('description_german', models.TextField(blank=True, default='')),
                ('description_ukrainian', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={},
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='description',
            new_name='description_english',
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='title',
            new_name='title_english',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_biography_english',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_biography_german',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_biography_ukrainian',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_paragraph_2_english',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_paragraph_2_german',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_paragraph_2_ukrainian',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_paragraph_3_english',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_paragraph_3_german',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_paragraph_3_ukrainian',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_title_english',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_title_german',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='about_title_ukrainian',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='painting',
            name='description_german',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='painting',
            name='description_ukrainian',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='painting',
            name='title_german',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='painting',
            name='title_ukrainian',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
