# Generated by Django 5.1.6 on 2026-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_aboutstatistic_education_experience_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description_english',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title_english',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
