import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
const inter = Inter({ subsets: ['latin'] })
import profilePic from "../../public/images/profile/profile-photo.png";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from "@/components/Icons"
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex flex-col lg:flex-row items-center justify-between w-full">
            <div className="w-full hidden md:block md:p-8 md:pt-0 lg:p-0 lg:w-1/2">
              <Image
                src={profilePic}
                alt="Dmytro"
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-full lg:w-1/2 flex flex-col items-center self-center lg:items-start">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-4xl !text-center md:!text-5xl lg:!text-6xl lg:!text-left"
              />
              <p className="my-4 text-center md:text-left text-xs font-medium md:text-sm lg:text-base">
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className="flex items-center self-center m-2 lg:self-start">
                <a
                  href="/dummy.pdf"
                  target='_blank'
              className="flex items-center bg-dark text-light p-2 px-4 rounded-lg text-base font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light lg:p-2.5 lg:px-6 lg:text-lg"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </a>

                <a
                  href="mailto:olyachumbash@gmail.com"
                  target='_blank'
                  className="ml-4 text-base font-medium capitalize text-dark underline dark:text-light lg:text-lg"
                >
                  Contact
                </a>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24  md:hidden lg:inline-block">
          <Image src={lightBulb} alt="" className="w-full h-auto" />
        </div>
      </main>
    </>
  )
}
